name: Deploy Campus Dual Utils library
on:
  workflow_dispatch:
    inputs:
      custom-version:
        type: string
        description: 'Optional. If you want it to have an additional specific version other than 99.9.9-SNAPSHOT, write it down.'
        required: false